# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dfubdkH7boOZOLL_aASkn3sPl2MBCMT
"""

from fastapi import FastAPI
from fastapi.responses import FileResponse
from pydantic import BaseModel
from TTS.api import TTS
import uuid
import os

app = FastAPI()

# تحميل الموديل
tts = TTS(model_name="tts_models/en/ljspeech/tacotron2-DDC", progress_bar=False, gpu=False)

class TextInput(BaseModel):
    text: str

@app.post("/speak")
def speak(input_text: TextInput):
    os.makedirs("output", exist_ok=True)
    filename = f"{uuid.uuid4().hex}.wav"
    path = f"output/{filename}"
    tts.tts_to_file(text=input_text.text, file_path=path)
    return FileResponse(path, media_type="audio/wav", filename=filename)

